#!/bin/bash

### BEGIN INIT INFO
# Provides: startup
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: startup
### END INIT INFO

sudo sh /home/Justin/auto-config/auto-minion.sh
